/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TksRouteImport } from './routes/tks'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as ObrigadoRouteImport } from './routes/obrigado'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as BuscaRouteImport } from './routes/busca'
import { Route as AdsbRouteImport } from './routes/adsb'
import { Route as AdsaRouteImport } from './routes/adsa'
import { Route as AdsRouteImport } from './routes/ads'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CrmIndexRouteImport } from './routes/crm.index'
import { Route as CasesIndexRouteImport } from './routes/cases.index'
import { Route as VSlugRouteImport } from './routes/v.$slug'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as CrmWhatsappRouteImport } from './routes/crm.whatsapp'
import { Route as CrmVideosRouteImport } from './routes/crm.videos'
import { Route as CrmTarefasRouteImport } from './routes/crm.tarefas'
import { Route as CrmKanbanRouteImport } from './routes/crm.kanban'
import { Route as CrmGravadorRouteImport } from './routes/crm.gravador'
import { Route as CrmDashboardRouteImport } from './routes/crm.dashboard'
import { Route as CrmAbRouteImport } from './routes/crm.ab'
import { Route as CasesSlugRouteImport } from './routes/cases.$slug'
import { Route as CrmPropostasIndexRouteImport } from './routes/crm.propostas.index'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as CrmPropostasIdRouteImport } from './routes/crm.propostas.$id'
import { Route as ApiPublicPropostaRouteImport } from './routes/api/public/proposta'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicWhatsappWebhookRouteImport } from './routes/api/public/whatsapp/webhook'
import { Route as ApiPublicWhatsappProcessRouteImport } from './routes/api/public/whatsapp/process'
import { Route as ApiPublicWhatsappFollowupRouteImport } from './routes/api/public/whatsapp/followup'
import { Route as ApiPublicVideoTrackRouteImport } from './routes/api/public/video/track'
import { Route as ApiPublicVideoProcessRouteImport } from './routes/api/public/video/process'
import { Route as ApiPublicLeadsSubmitRouteImport } from './routes/api/public/leads/submit'
import { Route as ApiPublicCrmWhatsappRouteImport } from './routes/api/public/crm/whatsapp'
import { Route as ApiPublicCrmVideosRouteImport } from './routes/api/public/crm/videos'
import { Route as ApiPublicCrmTasksRouteImport } from './routes/api/public/crm/tasks'
import { Route as ApiPublicCrmProposalsRouteImport } from './routes/api/public/crm/proposals'
import { Route as ApiPublicCrmDataRouteImport } from './routes/api/public/crm/data'
import { Route as ApiPublicCrmAbRouteImport } from './routes/api/public/crm/ab'
import { Route as ApiPublicAbVisitRouteImport } from './routes/api/public/ab/visit'

const TksRoute = TksRouteImport.update({
  id: '/tks',
  path: '/tks',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrigadoRoute = ObrigadoRouteImport.update({
  id: '/obrigado',
  path: '/obrigado',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscaRoute = BuscaRouteImport.update({
  id: '/busca',
  path: '/busca',
  getParentRoute: () => rootRouteImport,
} as any)
const AdsbRoute = AdsbRouteImport.update({
  id: '/adsb',
  path: '/adsb',
  getParentRoute: () => rootRouteImport,
} as any)
const AdsaRoute = AdsaRouteImport.update({
  id: '/adsa',
  path: '/adsa',
  getParentRoute: () => rootRouteImport,
} as any)
const AdsRoute = AdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmIndexRoute = CrmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CrmRoute,
} as any)
const CasesIndexRoute = CasesIndexRouteImport.update({
  id: '/cases/',
  path: '/cases/',
  getParentRoute: () => rootRouteImport,
} as any)
const VSlugRoute = VSlugRouteImport.update({
  id: '/v/$slug',
  path: '/v/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmWhatsappRoute = CrmWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => CrmRoute,
} as any)
const CrmVideosRoute = CrmVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => CrmRoute,
} as any)
const CrmTarefasRoute = CrmTarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => CrmRoute,
} as any)
const CrmKanbanRoute = CrmKanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => CrmRoute,
} as any)
const CrmGravadorRoute = CrmGravadorRouteImport.update({
  id: '/gravador',
  path: '/gravador',
  getParentRoute: () => CrmRoute,
} as any)
const CrmDashboardRoute = CrmDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => CrmRoute,
} as any)
const CrmAbRoute = CrmAbRouteImport.update({
  id: '/ab',
  path: '/ab',
  getParentRoute: () => CrmRoute,
} as any)
const CasesSlugRoute = CasesSlugRouteImport.update({
  id: '/cases/$slug',
  path: '/cases/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmPropostasIndexRoute = CrmPropostasIndexRouteImport.update({
  id: '/propostas/',
  path: '/propostas/',
  getParentRoute: () => CrmRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmPropostasIdRoute = CrmPropostasIdRouteImport.update({
  id: '/propostas/$id',
  path: '/propostas/$id',
  getParentRoute: () => CrmRoute,
} as any)
const ApiPublicPropostaRoute = ApiPublicPropostaRouteImport.update({
  id: '/api/public/proposta',
  path: '/api/public/proposta',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWhatsappWebhookRoute =
  ApiPublicWhatsappWebhookRouteImport.update({
    id: '/api/public/whatsapp/webhook',
    path: '/api/public/whatsapp/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWhatsappProcessRoute =
  ApiPublicWhatsappProcessRouteImport.update({
    id: '/api/public/whatsapp/process',
    path: '/api/public/whatsapp/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWhatsappFollowupRoute =
  ApiPublicWhatsappFollowupRouteImport.update({
    id: '/api/public/whatsapp/followup',
    path: '/api/public/whatsapp/followup',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicVideoTrackRoute = ApiPublicVideoTrackRouteImport.update({
  id: '/api/public/video/track',
  path: '/api/public/video/track',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVideoProcessRoute = ApiPublicVideoProcessRouteImport.update({
  id: '/api/public/video/process',
  path: '/api/public/video/process',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLeadsSubmitRoute = ApiPublicLeadsSubmitRouteImport.update({
  id: '/api/public/leads/submit',
  path: '/api/public/leads/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCrmWhatsappRoute = ApiPublicCrmWhatsappRouteImport.update({
  id: '/api/public/crm/whatsapp',
  path: '/api/public/crm/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCrmVideosRoute = ApiPublicCrmVideosRouteImport.update({
  id: '/api/public/crm/videos',
  path: '/api/public/crm/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCrmTasksRoute = ApiPublicCrmTasksRouteImport.update({
  id: '/api/public/crm/tasks',
  path: '/api/public/crm/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCrmProposalsRoute = ApiPublicCrmProposalsRouteImport.update({
  id: '/api/public/crm/proposals',
  path: '/api/public/crm/proposals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCrmDataRoute = ApiPublicCrmDataRouteImport.update({
  id: '/api/public/crm/data',
  path: '/api/public/crm/data',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCrmAbRoute = ApiPublicCrmAbRouteImport.update({
  id: '/api/public/crm/ab',
  path: '/api/public/crm/ab',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAbVisitRoute = ApiPublicAbVisitRouteImport.update({
  id: '/api/public/ab/visit',
  path: '/api/public/ab/visit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ads': typeof AdsRoute
  '/adsa': typeof AdsaRoute
  '/adsb': typeof AdsbRoute
  '/busca': typeof BuscaRoute
  '/crm': typeof CrmRouteWithChildren
  '/obrigado': typeof ObrigadoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/tks': typeof TksRoute
  '/cases/$slug': typeof CasesSlugRoute
  '/crm/ab': typeof CrmAbRoute
  '/crm/dashboard': typeof CrmDashboardRoute
  '/crm/gravador': typeof CrmGravadorRoute
  '/crm/kanban': typeof CrmKanbanRoute
  '/crm/tarefas': typeof CrmTarefasRoute
  '/crm/videos': typeof CrmVideosRoute
  '/crm/whatsapp': typeof CrmWhatsappRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/p/$slug': typeof PSlugRoute
  '/v/$slug': typeof VSlugRoute
  '/cases/': typeof CasesIndexRoute
  '/crm/': typeof CrmIndexRoute
  '/api/public/proposta': typeof ApiPublicPropostaRoute
  '/crm/propostas/$id': typeof CrmPropostasIdRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/crm/propostas/': typeof CrmPropostasIndexRoute
  '/api/public/ab/visit': typeof ApiPublicAbVisitRoute
  '/api/public/crm/ab': typeof ApiPublicCrmAbRoute
  '/api/public/crm/data': typeof ApiPublicCrmDataRoute
  '/api/public/crm/proposals': typeof ApiPublicCrmProposalsRoute
  '/api/public/crm/tasks': typeof ApiPublicCrmTasksRoute
  '/api/public/crm/videos': typeof ApiPublicCrmVideosRoute
  '/api/public/crm/whatsapp': typeof ApiPublicCrmWhatsappRoute
  '/api/public/leads/submit': typeof ApiPublicLeadsSubmitRoute
  '/api/public/video/process': typeof ApiPublicVideoProcessRoute
  '/api/public/video/track': typeof ApiPublicVideoTrackRoute
  '/api/public/whatsapp/followup': typeof ApiPublicWhatsappFollowupRoute
  '/api/public/whatsapp/process': typeof ApiPublicWhatsappProcessRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ads': typeof AdsRoute
  '/adsa': typeof AdsaRoute
  '/adsb': typeof AdsbRoute
  '/busca': typeof BuscaRoute
  '/obrigado': typeof ObrigadoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/tks': typeof TksRoute
  '/cases/$slug': typeof CasesSlugRoute
  '/crm/ab': typeof CrmAbRoute
  '/crm/dashboard': typeof CrmDashboardRoute
  '/crm/gravador': typeof CrmGravadorRoute
  '/crm/kanban': typeof CrmKanbanRoute
  '/crm/tarefas': typeof CrmTarefasRoute
  '/crm/videos': typeof CrmVideosRoute
  '/crm/whatsapp': typeof CrmWhatsappRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/p/$slug': typeof PSlugRoute
  '/v/$slug': typeof VSlugRoute
  '/cases': typeof CasesIndexRoute
  '/crm': typeof CrmIndexRoute
  '/api/public/proposta': typeof ApiPublicPropostaRoute
  '/crm/propostas/$id': typeof CrmPropostasIdRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/crm/propostas': typeof CrmPropostasIndexRoute
  '/api/public/ab/visit': typeof ApiPublicAbVisitRoute
  '/api/public/crm/ab': typeof ApiPublicCrmAbRoute
  '/api/public/crm/data': typeof ApiPublicCrmDataRoute
  '/api/public/crm/proposals': typeof ApiPublicCrmProposalsRoute
  '/api/public/crm/tasks': typeof ApiPublicCrmTasksRoute
  '/api/public/crm/videos': typeof ApiPublicCrmVideosRoute
  '/api/public/crm/whatsapp': typeof ApiPublicCrmWhatsappRoute
  '/api/public/leads/submit': typeof ApiPublicLeadsSubmitRoute
  '/api/public/video/process': typeof ApiPublicVideoProcessRoute
  '/api/public/video/track': typeof ApiPublicVideoTrackRoute
  '/api/public/whatsapp/followup': typeof ApiPublicWhatsappFollowupRoute
  '/api/public/whatsapp/process': typeof ApiPublicWhatsappProcessRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ads': typeof AdsRoute
  '/adsa': typeof AdsaRoute
  '/adsb': typeof AdsbRoute
  '/busca': typeof BuscaRoute
  '/crm': typeof CrmRouteWithChildren
  '/obrigado': typeof ObrigadoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/tks': typeof TksRoute
  '/cases/$slug': typeof CasesSlugRoute
  '/crm/ab': typeof CrmAbRoute
  '/crm/dashboard': typeof CrmDashboardRoute
  '/crm/gravador': typeof CrmGravadorRoute
  '/crm/kanban': typeof CrmKanbanRoute
  '/crm/tarefas': typeof CrmTarefasRoute
  '/crm/videos': typeof CrmVideosRoute
  '/crm/whatsapp': typeof CrmWhatsappRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/p/$slug': typeof PSlugRoute
  '/v/$slug': typeof VSlugRoute
  '/cases/': typeof CasesIndexRoute
  '/crm/': typeof CrmIndexRoute
  '/api/public/proposta': typeof ApiPublicPropostaRoute
  '/crm/propostas/$id': typeof CrmPropostasIdRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/crm/propostas/': typeof CrmPropostasIndexRoute
  '/api/public/ab/visit': typeof ApiPublicAbVisitRoute
  '/api/public/crm/ab': typeof ApiPublicCrmAbRoute
  '/api/public/crm/data': typeof ApiPublicCrmDataRoute
  '/api/public/crm/proposals': typeof ApiPublicCrmProposalsRoute
  '/api/public/crm/tasks': typeof ApiPublicCrmTasksRoute
  '/api/public/crm/videos': typeof ApiPublicCrmVideosRoute
  '/api/public/crm/whatsapp': typeof ApiPublicCrmWhatsappRoute
  '/api/public/leads/submit': typeof ApiPublicLeadsSubmitRoute
  '/api/public/video/process': typeof ApiPublicVideoProcessRoute
  '/api/public/video/track': typeof ApiPublicVideoTrackRoute
  '/api/public/whatsapp/followup': typeof ApiPublicWhatsappFollowupRoute
  '/api/public/whatsapp/process': typeof ApiPublicWhatsappProcessRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ads'
    | '/adsa'
    | '/adsb'
    | '/busca'
    | '/crm'
    | '/obrigado'
    | '/privacidade'
    | '/tks'
    | '/cases/$slug'
    | '/crm/ab'
    | '/crm/dashboard'
    | '/crm/gravador'
    | '/crm/kanban'
    | '/crm/tarefas'
    | '/crm/videos'
    | '/crm/whatsapp'
    | '/email/unsubscribe'
    | '/p/$slug'
    | '/v/$slug'
    | '/cases/'
    | '/crm/'
    | '/api/public/proposta'
    | '/crm/propostas/$id'
    | '/lovable/email/suppression'
    | '/crm/propostas/'
    | '/api/public/ab/visit'
    | '/api/public/crm/ab'
    | '/api/public/crm/data'
    | '/api/public/crm/proposals'
    | '/api/public/crm/tasks'
    | '/api/public/crm/videos'
    | '/api/public/crm/whatsapp'
    | '/api/public/leads/submit'
    | '/api/public/video/process'
    | '/api/public/video/track'
    | '/api/public/whatsapp/followup'
    | '/api/public/whatsapp/process'
    | '/api/public/whatsapp/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ads'
    | '/adsa'
    | '/adsb'
    | '/busca'
    | '/obrigado'
    | '/privacidade'
    | '/tks'
    | '/cases/$slug'
    | '/crm/ab'
    | '/crm/dashboard'
    | '/crm/gravador'
    | '/crm/kanban'
    | '/crm/tarefas'
    | '/crm/videos'
    | '/crm/whatsapp'
    | '/email/unsubscribe'
    | '/p/$slug'
    | '/v/$slug'
    | '/cases'
    | '/crm'
    | '/api/public/proposta'
    | '/crm/propostas/$id'
    | '/lovable/email/suppression'
    | '/crm/propostas'
    | '/api/public/ab/visit'
    | '/api/public/crm/ab'
    | '/api/public/crm/data'
    | '/api/public/crm/proposals'
    | '/api/public/crm/tasks'
    | '/api/public/crm/videos'
    | '/api/public/crm/whatsapp'
    | '/api/public/leads/submit'
    | '/api/public/video/process'
    | '/api/public/video/track'
    | '/api/public/whatsapp/followup'
    | '/api/public/whatsapp/process'
    | '/api/public/whatsapp/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/ads'
    | '/adsa'
    | '/adsb'
    | '/busca'
    | '/crm'
    | '/obrigado'
    | '/privacidade'
    | '/tks'
    | '/cases/$slug'
    | '/crm/ab'
    | '/crm/dashboard'
    | '/crm/gravador'
    | '/crm/kanban'
    | '/crm/tarefas'
    | '/crm/videos'
    | '/crm/whatsapp'
    | '/email/unsubscribe'
    | '/p/$slug'
    | '/v/$slug'
    | '/cases/'
    | '/crm/'
    | '/api/public/proposta'
    | '/crm/propostas/$id'
    | '/lovable/email/suppression'
    | '/crm/propostas/'
    | '/api/public/ab/visit'
    | '/api/public/crm/ab'
    | '/api/public/crm/data'
    | '/api/public/crm/proposals'
    | '/api/public/crm/tasks'
    | '/api/public/crm/videos'
    | '/api/public/crm/whatsapp'
    | '/api/public/leads/submit'
    | '/api/public/video/process'
    | '/api/public/video/track'
    | '/api/public/whatsapp/followup'
    | '/api/public/whatsapp/process'
    | '/api/public/whatsapp/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdsRoute: typeof AdsRoute
  AdsaRoute: typeof AdsaRoute
  AdsbRoute: typeof AdsbRoute
  BuscaRoute: typeof BuscaRoute
  CrmRoute: typeof CrmRouteWithChildren
  ObrigadoRoute: typeof ObrigadoRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  TksRoute: typeof TksRoute
  CasesSlugRoute: typeof CasesSlugRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  PSlugRoute: typeof PSlugRoute
  VSlugRoute: typeof VSlugRoute
  CasesIndexRoute: typeof CasesIndexRoute
  ApiPublicPropostaRoute: typeof ApiPublicPropostaRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicAbVisitRoute: typeof ApiPublicAbVisitRoute
  ApiPublicCrmAbRoute: typeof ApiPublicCrmAbRoute
  ApiPublicCrmDataRoute: typeof ApiPublicCrmDataRoute
  ApiPublicCrmProposalsRoute: typeof ApiPublicCrmProposalsRoute
  ApiPublicCrmTasksRoute: typeof ApiPublicCrmTasksRoute
  ApiPublicCrmVideosRoute: typeof ApiPublicCrmVideosRoute
  ApiPublicCrmWhatsappRoute: typeof ApiPublicCrmWhatsappRoute
  ApiPublicLeadsSubmitRoute: typeof ApiPublicLeadsSubmitRoute
  ApiPublicVideoProcessRoute: typeof ApiPublicVideoProcessRoute
  ApiPublicVideoTrackRoute: typeof ApiPublicVideoTrackRoute
  ApiPublicWhatsappFollowupRoute: typeof ApiPublicWhatsappFollowupRoute
  ApiPublicWhatsappProcessRoute: typeof ApiPublicWhatsappProcessRoute
  ApiPublicWhatsappWebhookRoute: typeof ApiPublicWhatsappWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tks': {
      id: '/tks'
      path: '/tks'
      fullPath: '/tks'
      preLoaderRoute: typeof TksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obrigado': {
      id: '/obrigado'
      path: '/obrigado'
      fullPath: '/obrigado'
      preLoaderRoute: typeof ObrigadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/busca': {
      id: '/busca'
      path: '/busca'
      fullPath: '/busca'
      preLoaderRoute: typeof BuscaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adsb': {
      id: '/adsb'
      path: '/adsb'
      fullPath: '/adsb'
      preLoaderRoute: typeof AdsbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adsa': {
      id: '/adsa'
      path: '/adsa'
      fullPath: '/adsa'
      preLoaderRoute: typeof AdsaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ads': {
      id: '/ads'
      path: '/ads'
      fullPath: '/ads'
      preLoaderRoute: typeof AdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/': {
      id: '/crm/'
      path: '/'
      fullPath: '/crm/'
      preLoaderRoute: typeof CrmIndexRouteImport
      parentRoute: typeof CrmRoute
    }
    '/cases/': {
      id: '/cases/'
      path: '/cases'
      fullPath: '/cases/'
      preLoaderRoute: typeof CasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v/$slug': {
      id: '/v/$slug'
      path: '/v/$slug'
      fullPath: '/v/$slug'
      preLoaderRoute: typeof VSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/whatsapp': {
      id: '/crm/whatsapp'
      path: '/whatsapp'
      fullPath: '/crm/whatsapp'
      preLoaderRoute: typeof CrmWhatsappRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/videos': {
      id: '/crm/videos'
      path: '/videos'
      fullPath: '/crm/videos'
      preLoaderRoute: typeof CrmVideosRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/tarefas': {
      id: '/crm/tarefas'
      path: '/tarefas'
      fullPath: '/crm/tarefas'
      preLoaderRoute: typeof CrmTarefasRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/kanban': {
      id: '/crm/kanban'
      path: '/kanban'
      fullPath: '/crm/kanban'
      preLoaderRoute: typeof CrmKanbanRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/gravador': {
      id: '/crm/gravador'
      path: '/gravador'
      fullPath: '/crm/gravador'
      preLoaderRoute: typeof CrmGravadorRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/dashboard': {
      id: '/crm/dashboard'
      path: '/dashboard'
      fullPath: '/crm/dashboard'
      preLoaderRoute: typeof CrmDashboardRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/ab': {
      id: '/crm/ab'
      path: '/ab'
      fullPath: '/crm/ab'
      preLoaderRoute: typeof CrmAbRouteImport
      parentRoute: typeof CrmRoute
    }
    '/cases/$slug': {
      id: '/cases/$slug'
      path: '/cases/$slug'
      fullPath: '/cases/$slug'
      preLoaderRoute: typeof CasesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/propostas/': {
      id: '/crm/propostas/'
      path: '/propostas'
      fullPath: '/crm/propostas/'
      preLoaderRoute: typeof CrmPropostasIndexRouteImport
      parentRoute: typeof CrmRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/propostas/$id': {
      id: '/crm/propostas/$id'
      path: '/propostas/$id'
      fullPath: '/crm/propostas/$id'
      preLoaderRoute: typeof CrmPropostasIdRouteImport
      parentRoute: typeof CrmRoute
    }
    '/api/public/proposta': {
      id: '/api/public/proposta'
      path: '/api/public/proposta'
      fullPath: '/api/public/proposta'
      preLoaderRoute: typeof ApiPublicPropostaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp/webhook': {
      id: '/api/public/whatsapp/webhook'
      path: '/api/public/whatsapp/webhook'
      fullPath: '/api/public/whatsapp/webhook'
      preLoaderRoute: typeof ApiPublicWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp/process': {
      id: '/api/public/whatsapp/process'
      path: '/api/public/whatsapp/process'
      fullPath: '/api/public/whatsapp/process'
      preLoaderRoute: typeof ApiPublicWhatsappProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp/followup': {
      id: '/api/public/whatsapp/followup'
      path: '/api/public/whatsapp/followup'
      fullPath: '/api/public/whatsapp/followup'
      preLoaderRoute: typeof ApiPublicWhatsappFollowupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/video/track': {
      id: '/api/public/video/track'
      path: '/api/public/video/track'
      fullPath: '/api/public/video/track'
      preLoaderRoute: typeof ApiPublicVideoTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/video/process': {
      id: '/api/public/video/process'
      path: '/api/public/video/process'
      fullPath: '/api/public/video/process'
      preLoaderRoute: typeof ApiPublicVideoProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/leads/submit': {
      id: '/api/public/leads/submit'
      path: '/api/public/leads/submit'
      fullPath: '/api/public/leads/submit'
      preLoaderRoute: typeof ApiPublicLeadsSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/crm/whatsapp': {
      id: '/api/public/crm/whatsapp'
      path: '/api/public/crm/whatsapp'
      fullPath: '/api/public/crm/whatsapp'
      preLoaderRoute: typeof ApiPublicCrmWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/crm/videos': {
      id: '/api/public/crm/videos'
      path: '/api/public/crm/videos'
      fullPath: '/api/public/crm/videos'
      preLoaderRoute: typeof ApiPublicCrmVideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/crm/tasks': {
      id: '/api/public/crm/tasks'
      path: '/api/public/crm/tasks'
      fullPath: '/api/public/crm/tasks'
      preLoaderRoute: typeof ApiPublicCrmTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/crm/proposals': {
      id: '/api/public/crm/proposals'
      path: '/api/public/crm/proposals'
      fullPath: '/api/public/crm/proposals'
      preLoaderRoute: typeof ApiPublicCrmProposalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/crm/data': {
      id: '/api/public/crm/data'
      path: '/api/public/crm/data'
      fullPath: '/api/public/crm/data'
      preLoaderRoute: typeof ApiPublicCrmDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/crm/ab': {
      id: '/api/public/crm/ab'
      path: '/api/public/crm/ab'
      fullPath: '/api/public/crm/ab'
      preLoaderRoute: typeof ApiPublicCrmAbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ab/visit': {
      id: '/api/public/ab/visit'
      path: '/api/public/ab/visit'
      fullPath: '/api/public/ab/visit'
      preLoaderRoute: typeof ApiPublicAbVisitRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CrmRouteChildren {
  CrmAbRoute: typeof CrmAbRoute
  CrmDashboardRoute: typeof CrmDashboardRoute
  CrmGravadorRoute: typeof CrmGravadorRoute
  CrmKanbanRoute: typeof CrmKanbanRoute
  CrmTarefasRoute: typeof CrmTarefasRoute
  CrmVideosRoute: typeof CrmVideosRoute
  CrmWhatsappRoute: typeof CrmWhatsappRoute
  CrmIndexRoute: typeof CrmIndexRoute
  CrmPropostasIdRoute: typeof CrmPropostasIdRoute
  CrmPropostasIndexRoute: typeof CrmPropostasIndexRoute
}

const CrmRouteChildren: CrmRouteChildren = {
  CrmAbRoute: CrmAbRoute,
  CrmDashboardRoute: CrmDashboardRoute,
  CrmGravadorRoute: CrmGravadorRoute,
  CrmKanbanRoute: CrmKanbanRoute,
  CrmTarefasRoute: CrmTarefasRoute,
  CrmVideosRoute: CrmVideosRoute,
  CrmWhatsappRoute: CrmWhatsappRoute,
  CrmIndexRoute: CrmIndexRoute,
  CrmPropostasIdRoute: CrmPropostasIdRoute,
  CrmPropostasIndexRoute: CrmPropostasIndexRoute,
}

const CrmRouteWithChildren = CrmRoute._addFileChildren(CrmRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdsRoute: AdsRoute,
  AdsaRoute: AdsaRoute,
  AdsbRoute: AdsbRoute,
  BuscaRoute: BuscaRoute,
  CrmRoute: CrmRouteWithChildren,
  ObrigadoRoute: ObrigadoRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  TksRoute: TksRoute,
  CasesSlugRoute: CasesSlugRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  PSlugRoute: PSlugRoute,
  VSlugRoute: VSlugRoute,
  CasesIndexRoute: CasesIndexRoute,
  ApiPublicPropostaRoute: ApiPublicPropostaRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicAbVisitRoute: ApiPublicAbVisitRoute,
  ApiPublicCrmAbRoute: ApiPublicCrmAbRoute,
  ApiPublicCrmDataRoute: ApiPublicCrmDataRoute,
  ApiPublicCrmProposalsRoute: ApiPublicCrmProposalsRoute,
  ApiPublicCrmTasksRoute: ApiPublicCrmTasksRoute,
  ApiPublicCrmVideosRoute: ApiPublicCrmVideosRoute,
  ApiPublicCrmWhatsappRoute: ApiPublicCrmWhatsappRoute,
  ApiPublicLeadsSubmitRoute: ApiPublicLeadsSubmitRoute,
  ApiPublicVideoProcessRoute: ApiPublicVideoProcessRoute,
  ApiPublicVideoTrackRoute: ApiPublicVideoTrackRoute,
  ApiPublicWhatsappFollowupRoute: ApiPublicWhatsappFollowupRoute,
  ApiPublicWhatsappProcessRoute: ApiPublicWhatsappProcessRoute,
  ApiPublicWhatsappWebhookRoute: ApiPublicWhatsappWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
