/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TksRouteImport } from './routes/tks'
import { Route as ObrigadoRouteImport } from './routes/obrigado'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as AdsRouteImport } from './routes/ads'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CrmIndexRouteImport } from './routes/crm.index'
import { Route as CasesIndexRouteImport } from './routes/cases.index'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as CrmWhatsappRouteImport } from './routes/crm.whatsapp'
import { Route as CrmTarefasRouteImport } from './routes/crm.tarefas'
import { Route as CrmKanbanRouteImport } from './routes/crm.kanban'
import { Route as CasesSlugRouteImport } from './routes/cases.$slug'
import { Route as CrmPropostasIndexRouteImport } from './routes/crm.propostas.index'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as CrmPropostasIdRouteImport } from './routes/crm.propostas.$id'
import { Route as ApiPublicPropostaRouteImport } from './routes/api/public/proposta'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicLeadsSubmitRouteImport } from './routes/api/public/leads/submit'
import { Route as ApiPublicCrmWhatsappRouteImport } from './routes/api/public/crm/whatsapp'
import { Route as ApiPublicCrmTasksRouteImport } from './routes/api/public/crm/tasks'
import { Route as ApiPublicCrmProposalsRouteImport } from './routes/api/public/crm/proposals'
import { Route as ApiPublicCrmDataRouteImport } from './routes/api/public/crm/data'

const TksRoute = TksRouteImport.update({
  id: '/tks',
  path: '/tks',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrigadoRoute = ObrigadoRouteImport.update({
  id: '/obrigado',
  path: '/obrigado',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const AdsRoute = AdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmIndexRoute = CrmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CrmRoute,
} as any)
const CasesIndexRoute = CasesIndexRouteImport.update({
  id: '/cases/',
  path: '/cases/',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmWhatsappRoute = CrmWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => CrmRoute,
} as any)
const CrmTarefasRoute = CrmTarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => CrmRoute,
} as any)
const CrmKanbanRoute = CrmKanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => CrmRoute,
} as any)
const CasesSlugRoute = CasesSlugRouteImport.update({
  id: '/cases/$slug',
  path: '/cases/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmPropostasIndexRoute = CrmPropostasIndexRouteImport.update({
  id: '/propostas/',
  path: '/propostas/',
  getParentRoute: () => CrmRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmPropostasIdRoute = CrmPropostasIdRouteImport.update({
  id: '/propostas/$id',
  path: '/propostas/$id',
  getParentRoute: () => CrmRoute,
} as any)
const ApiPublicPropostaRoute = ApiPublicPropostaRouteImport.update({
  id: '/api/public/proposta',
  path: '/api/public/proposta',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicLeadsSubmitRoute = ApiPublicLeadsSubmitRouteImport.update({
  id: '/api/public/leads/submit',
  path: '/api/public/leads/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCrmWhatsappRoute = ApiPublicCrmWhatsappRouteImport.update({
  id: '/api/public/crm/whatsapp',
  path: '/api/public/crm/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCrmTasksRoute = ApiPublicCrmTasksRouteImport.update({
  id: '/api/public/crm/tasks',
  path: '/api/public/crm/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCrmProposalsRoute = ApiPublicCrmProposalsRouteImport.update({
  id: '/api/public/crm/proposals',
  path: '/api/public/crm/proposals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCrmDataRoute = ApiPublicCrmDataRouteImport.update({
  id: '/api/public/crm/data',
  path: '/api/public/crm/data',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ads': typeof AdsRoute
  '/crm': typeof CrmRouteWithChildren
  '/obrigado': typeof ObrigadoRoute
  '/tks': typeof TksRoute
  '/cases/$slug': typeof CasesSlugRoute
  '/crm/kanban': typeof CrmKanbanRoute
  '/crm/tarefas': typeof CrmTarefasRoute
  '/crm/whatsapp': typeof CrmWhatsappRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/p/$slug': typeof PSlugRoute
  '/cases/': typeof CasesIndexRoute
  '/crm/': typeof CrmIndexRoute
  '/api/public/proposta': typeof ApiPublicPropostaRoute
  '/crm/propostas/$id': typeof CrmPropostasIdRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/crm/propostas/': typeof CrmPropostasIndexRoute
  '/api/public/crm/data': typeof ApiPublicCrmDataRoute
  '/api/public/crm/proposals': typeof ApiPublicCrmProposalsRoute
  '/api/public/crm/tasks': typeof ApiPublicCrmTasksRoute
  '/api/public/crm/whatsapp': typeof ApiPublicCrmWhatsappRoute
  '/api/public/leads/submit': typeof ApiPublicLeadsSubmitRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ads': typeof AdsRoute
  '/obrigado': typeof ObrigadoRoute
  '/tks': typeof TksRoute
  '/cases/$slug': typeof CasesSlugRoute
  '/crm/kanban': typeof CrmKanbanRoute
  '/crm/tarefas': typeof CrmTarefasRoute
  '/crm/whatsapp': typeof CrmWhatsappRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/p/$slug': typeof PSlugRoute
  '/cases': typeof CasesIndexRoute
  '/crm': typeof CrmIndexRoute
  '/api/public/proposta': typeof ApiPublicPropostaRoute
  '/crm/propostas/$id': typeof CrmPropostasIdRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/crm/propostas': typeof CrmPropostasIndexRoute
  '/api/public/crm/data': typeof ApiPublicCrmDataRoute
  '/api/public/crm/proposals': typeof ApiPublicCrmProposalsRoute
  '/api/public/crm/tasks': typeof ApiPublicCrmTasksRoute
  '/api/public/crm/whatsapp': typeof ApiPublicCrmWhatsappRoute
  '/api/public/leads/submit': typeof ApiPublicLeadsSubmitRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ads': typeof AdsRoute
  '/crm': typeof CrmRouteWithChildren
  '/obrigado': typeof ObrigadoRoute
  '/tks': typeof TksRoute
  '/cases/$slug': typeof CasesSlugRoute
  '/crm/kanban': typeof CrmKanbanRoute
  '/crm/tarefas': typeof CrmTarefasRoute
  '/crm/whatsapp': typeof CrmWhatsappRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/p/$slug': typeof PSlugRoute
  '/cases/': typeof CasesIndexRoute
  '/crm/': typeof CrmIndexRoute
  '/api/public/proposta': typeof ApiPublicPropostaRoute
  '/crm/propostas/$id': typeof CrmPropostasIdRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/crm/propostas/': typeof CrmPropostasIndexRoute
  '/api/public/crm/data': typeof ApiPublicCrmDataRoute
  '/api/public/crm/proposals': typeof ApiPublicCrmProposalsRoute
  '/api/public/crm/tasks': typeof ApiPublicCrmTasksRoute
  '/api/public/crm/whatsapp': typeof ApiPublicCrmWhatsappRoute
  '/api/public/leads/submit': typeof ApiPublicLeadsSubmitRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ads'
    | '/crm'
    | '/obrigado'
    | '/tks'
    | '/cases/$slug'
    | '/crm/kanban'
    | '/crm/tarefas'
    | '/crm/whatsapp'
    | '/email/unsubscribe'
    | '/p/$slug'
    | '/cases/'
    | '/crm/'
    | '/api/public/proposta'
    | '/crm/propostas/$id'
    | '/lovable/email/suppression'
    | '/crm/propostas/'
    | '/api/public/crm/data'
    | '/api/public/crm/proposals'
    | '/api/public/crm/tasks'
    | '/api/public/crm/whatsapp'
    | '/api/public/leads/submit'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ads'
    | '/obrigado'
    | '/tks'
    | '/cases/$slug'
    | '/crm/kanban'
    | '/crm/tarefas'
    | '/crm/whatsapp'
    | '/email/unsubscribe'
    | '/p/$slug'
    | '/cases'
    | '/crm'
    | '/api/public/proposta'
    | '/crm/propostas/$id'
    | '/lovable/email/suppression'
    | '/crm/propostas'
    | '/api/public/crm/data'
    | '/api/public/crm/proposals'
    | '/api/public/crm/tasks'
    | '/api/public/crm/whatsapp'
    | '/api/public/leads/submit'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/ads'
    | '/crm'
    | '/obrigado'
    | '/tks'
    | '/cases/$slug'
    | '/crm/kanban'
    | '/crm/tarefas'
    | '/crm/whatsapp'
    | '/email/unsubscribe'
    | '/p/$slug'
    | '/cases/'
    | '/crm/'
    | '/api/public/proposta'
    | '/crm/propostas/$id'
    | '/lovable/email/suppression'
    | '/crm/propostas/'
    | '/api/public/crm/data'
    | '/api/public/crm/proposals'
    | '/api/public/crm/tasks'
    | '/api/public/crm/whatsapp'
    | '/api/public/leads/submit'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdsRoute: typeof AdsRoute
  CrmRoute: typeof CrmRouteWithChildren
  ObrigadoRoute: typeof ObrigadoRoute
  TksRoute: typeof TksRoute
  CasesSlugRoute: typeof CasesSlugRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  PSlugRoute: typeof PSlugRoute
  CasesIndexRoute: typeof CasesIndexRoute
  ApiPublicPropostaRoute: typeof ApiPublicPropostaRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicCrmDataRoute: typeof ApiPublicCrmDataRoute
  ApiPublicCrmProposalsRoute: typeof ApiPublicCrmProposalsRoute
  ApiPublicCrmTasksRoute: typeof ApiPublicCrmTasksRoute
  ApiPublicCrmWhatsappRoute: typeof ApiPublicCrmWhatsappRoute
  ApiPublicLeadsSubmitRoute: typeof ApiPublicLeadsSubmitRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tks': {
      id: '/tks'
      path: '/tks'
      fullPath: '/tks'
      preLoaderRoute: typeof TksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obrigado': {
      id: '/obrigado'
      path: '/obrigado'
      fullPath: '/obrigado'
      preLoaderRoute: typeof ObrigadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ads': {
      id: '/ads'
      path: '/ads'
      fullPath: '/ads'
      preLoaderRoute: typeof AdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/': {
      id: '/crm/'
      path: '/'
      fullPath: '/crm/'
      preLoaderRoute: typeof CrmIndexRouteImport
      parentRoute: typeof CrmRoute
    }
    '/cases/': {
      id: '/cases/'
      path: '/cases'
      fullPath: '/cases/'
      preLoaderRoute: typeof CasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/whatsapp': {
      id: '/crm/whatsapp'
      path: '/whatsapp'
      fullPath: '/crm/whatsapp'
      preLoaderRoute: typeof CrmWhatsappRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/tarefas': {
      id: '/crm/tarefas'
      path: '/tarefas'
      fullPath: '/crm/tarefas'
      preLoaderRoute: typeof CrmTarefasRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/kanban': {
      id: '/crm/kanban'
      path: '/kanban'
      fullPath: '/crm/kanban'
      preLoaderRoute: typeof CrmKanbanRouteImport
      parentRoute: typeof CrmRoute
    }
    '/cases/$slug': {
      id: '/cases/$slug'
      path: '/cases/$slug'
      fullPath: '/cases/$slug'
      preLoaderRoute: typeof CasesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/propostas/': {
      id: '/crm/propostas/'
      path: '/propostas'
      fullPath: '/crm/propostas/'
      preLoaderRoute: typeof CrmPropostasIndexRouteImport
      parentRoute: typeof CrmRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/propostas/$id': {
      id: '/crm/propostas/$id'
      path: '/propostas/$id'
      fullPath: '/crm/propostas/$id'
      preLoaderRoute: typeof CrmPropostasIdRouteImport
      parentRoute: typeof CrmRoute
    }
    '/api/public/proposta': {
      id: '/api/public/proposta'
      path: '/api/public/proposta'
      fullPath: '/api/public/proposta'
      preLoaderRoute: typeof ApiPublicPropostaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/leads/submit': {
      id: '/api/public/leads/submit'
      path: '/api/public/leads/submit'
      fullPath: '/api/public/leads/submit'
      preLoaderRoute: typeof ApiPublicLeadsSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/crm/whatsapp': {
      id: '/api/public/crm/whatsapp'
      path: '/api/public/crm/whatsapp'
      fullPath: '/api/public/crm/whatsapp'
      preLoaderRoute: typeof ApiPublicCrmWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/crm/tasks': {
      id: '/api/public/crm/tasks'
      path: '/api/public/crm/tasks'
      fullPath: '/api/public/crm/tasks'
      preLoaderRoute: typeof ApiPublicCrmTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/crm/proposals': {
      id: '/api/public/crm/proposals'
      path: '/api/public/crm/proposals'
      fullPath: '/api/public/crm/proposals'
      preLoaderRoute: typeof ApiPublicCrmProposalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/crm/data': {
      id: '/api/public/crm/data'
      path: '/api/public/crm/data'
      fullPath: '/api/public/crm/data'
      preLoaderRoute: typeof ApiPublicCrmDataRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CrmRouteChildren {
  CrmKanbanRoute: typeof CrmKanbanRoute
  CrmTarefasRoute: typeof CrmTarefasRoute
  CrmWhatsappRoute: typeof CrmWhatsappRoute
  CrmIndexRoute: typeof CrmIndexRoute
  CrmPropostasIdRoute: typeof CrmPropostasIdRoute
  CrmPropostasIndexRoute: typeof CrmPropostasIndexRoute
}

const CrmRouteChildren: CrmRouteChildren = {
  CrmKanbanRoute: CrmKanbanRoute,
  CrmTarefasRoute: CrmTarefasRoute,
  CrmWhatsappRoute: CrmWhatsappRoute,
  CrmIndexRoute: CrmIndexRoute,
  CrmPropostasIdRoute: CrmPropostasIdRoute,
  CrmPropostasIndexRoute: CrmPropostasIndexRoute,
}

const CrmRouteWithChildren = CrmRoute._addFileChildren(CrmRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdsRoute: AdsRoute,
  CrmRoute: CrmRouteWithChildren,
  ObrigadoRoute: ObrigadoRoute,
  TksRoute: TksRoute,
  CasesSlugRoute: CasesSlugRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  PSlugRoute: PSlugRoute,
  CasesIndexRoute: CasesIndexRoute,
  ApiPublicPropostaRoute: ApiPublicPropostaRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicCrmDataRoute: ApiPublicCrmDataRoute,
  ApiPublicCrmProposalsRoute: ApiPublicCrmProposalsRoute,
  ApiPublicCrmTasksRoute: ApiPublicCrmTasksRoute,
  ApiPublicCrmWhatsappRoute: ApiPublicCrmWhatsappRoute,
  ApiPublicLeadsSubmitRoute: ApiPublicLeadsSubmitRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
